f=open('ui/gui.py',encoding='utf-8')
c=f.read()
f.close()
c=c.replace('GROUP_PREFIX   = "__SG__"','GROUP_PREFIX   = "__SG__"\nCALL_PREFIX    = "\x00SC\x00"')
f=open('ui/gui.py','w',encoding='utf-8')
f.write(c)
f.close()
print('Done:', 'CALL_PREFIX' in c)
