f=open('ui/gui.py',encoding='utf-8')
c=f.read()
f.close()
c=c.replace('CALL_PREFIX    = "\x00SC\x00"','CALL_PREFIX    = "\\x00SC\\x00"')
f=open('ui/gui.py','w',encoding='utf-8')
f.write(c)
f.close()
print('Fixed:', 'CALL_PREFIX' in c)
